name: woye_user
description: "A new Flutter project."

publish_to: "none" # 3.24.3

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  image_picker:
  pinput: ^5.0.0
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.8
  animated_svg: ^2.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  country_code_picker: ^3.0.0
  sticky_headers: ^0.3.0+2
  another_xlider: ^3.0.2
  flutter_sticky_header: ^0.7.0
  otp_timer_button:
  loading_animation_widget: ^1.3.0
  flutter_dotenv: ^5.2.1
  firebase_database:
  flutter_facebook_auth: ^6.0.4
  flutter_local_notifications: ^17.1.2
  permission_handler:
  google_sign_in: ^6.2.1
  sign_in_with_apple:
  dotted_border: ^2.1.0
  get: ^4.6.6
  csc_picker:
  firebase_messaging: ^15.1.4
  location: ^7.0.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^27.1.58
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  flutter_image_compress: ^2.3.0
  custom_rating_bar: ^3.0.0
  cloud_firestore: ^5.5.1
  lottie: ^3.2.0
  flutter_typeahead: ^5.2.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_storage: ^2.1.1
  carousel_slider:
  colorful_safe_area: ^1.0.0
  image_cropper:
  app_links: ^6.4.0
  share_plus: ^10.1.4
  dio:
  open_file:
  path_provider:
  webview_flutter:
  firebase_crashlytics:
  url_launcher:
#  pay_with_paystack:
  pay_with_paystack: ^1.0.14
  uuid:
#  persistent_bottom_nav_bar:
  intl:
  dropdown_button2:
  another_flushbar:
#  sms_autofill: ^2.0.0
  package_info_plus: ^8.3.0
  google_nav_bar: ^5.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/lottieJson/
    - assets/.env
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: GilroyUltraLight
      fonts:
        - asset: assets/fonts/Gilroy-UltraLight.ttf
    - family: GilroyThin
      fonts:
        - asset: assets/fonts/Gilroy-Thin.ttf
    - family: GilroyLight
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: GilroySemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: GilroyExtraBold
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
    - family: GilroyHeavy
      fonts:
        - asset: assets/fonts/Gilroy-Heavy.ttf
    - family: GilroyBlack
      fonts:
        - asset: assets/fonts/Gilroy-Black.ttf
    - family: OnestBlack
      fonts:
        - asset: assets/fonts/Onest-Black.ttf
    - family: OnestBold
      fonts:
        - asset: assets/fonts/Onest-Bold.ttf
    - family: OnestExtraBold
      fonts:
        - asset: assets/fonts/Onest-ExtraBold.ttf
    - family: OnestExtraLight
      fonts:
        - asset: assets/fonts/Onest-ExtraLight.ttf
    - family: OnestLight
      fonts:
        - asset: assets/fonts/Onest-Light.ttf
    - family: OnestMedium
      fonts:
        - asset: assets/fonts/Onest-Medium.ttf
    - family: OnestRegular
      fonts:
        - asset: assets/fonts/Onest-Regular.ttf
    - family: OnestSemiBold
      fonts:
        - asset: assets/fonts/Onest-SemiBold.ttf
    - family: OnestThin
      fonts:
         - asset: assets/fonts/Onest-Thin.ttf